/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package communitycenter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andik
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    int i;
    String n;
    String e;
    
    public Menu() {
        initComponents();
        
    }
    
    public Menu(int id, String nama, String email) {
        initComponents();
        
        i = id;
        n = nama;
        e = email;
        
        labelNama.setText("Selamat Datang " + nama);
        labelEmail.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonBuku = new javax.swing.JButton();
        buttonBooking = new javax.swing.JButton();
        buttonMember = new javax.swing.JButton();
        buttonPinjam = new javax.swing.JButton();
        buttonAudio = new javax.swing.JButton();
        buttonToy = new javax.swing.JButton();
        buttonVideo = new javax.swing.JButton();
        buttonPoS = new javax.swing.JButton();
        buttonCoworkingSpace = new javax.swing.JButton();
        buttonLaporan = new javax.swing.JButton();
        buttonPengembalian = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBuku.setText("Buku");
        buttonBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBukuActionPerformed(evt);
            }
        });

        buttonBooking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBooking.setText("Booking");
        buttonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookingActionPerformed(evt);
            }
        });

        buttonMember.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMember.setText("Member");
        buttonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemberActionPerformed(evt);
            }
        });

        buttonPinjam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPinjam.setText("Pinjam");
        buttonPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPinjamActionPerformed(evt);
            }
        });

        buttonAudio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAudio.setText("Audio");
        buttonAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAudioActionPerformed(evt);
            }
        });

        buttonToy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonToy.setText("Toy");
        buttonToy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToyActionPerformed(evt);
            }
        });

        buttonVideo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonVideo.setText("Video");
        buttonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVideoActionPerformed(evt);
            }
        });

        buttonPoS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPoS.setText("Point of Sell");
        buttonPoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPoSActionPerformed(evt);
            }
        });

        buttonCoworkingSpace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCoworkingSpace.setText("Coworking Space");
        buttonCoworkingSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCoworkingSpaceActionPerformed(evt);
            }
        });

        buttonLaporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLaporan.setText("Laporan");
        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });

        buttonPengembalian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPengembalian.setText("Pengembalian");
        buttonPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPengembalianActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMMUNITY CENTER");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        buttonLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonVideo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(buttonToy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(buttonPinjam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(buttonBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(buttonMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                            .addGap(89, 89, 89)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCoworkingSpace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                .addComponent(buttonBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonPoS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(908, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCoworkingSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonToy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPoS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(buttonMember, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBukuActionPerformed
        // TODO add your handling code here:
        new Buku(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonBukuActionPerformed

    private void buttonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBookingActionPerformed
        // TODO add your handling code here:
        new Booking(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonBookingActionPerformed

    private void buttonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemberActionPerformed
        // TODO add your handling code here:
        new Member(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonMemberActionPerformed

    private void buttonPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPinjamActionPerformed
        // TODO add your handling code here:
        new Pinjam(i, n, e).setVisible(true);

        
        dispose();
    }//GEN-LAST:event_buttonPinjamActionPerformed

    private void buttonAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAudioActionPerformed
        // TODO add your handling code here:
        new ManageAudio(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonAudioActionPerformed

    private void buttonToyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToyActionPerformed
        // TODO add your handling code here:
        new ManageToy(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonToyActionPerformed

    private void buttonVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVideoActionPerformed
        // TODO add your handling code here:
        new ManageVideo(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonVideoActionPerformed

    private void buttonPoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPoSActionPerformed
        // TODO add your handling code here:
        new PointofSell(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonPoSActionPerformed

    private void buttonCoworkingSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCoworkingSpaceActionPerformed
        // TODO add your handling code here:
        new CoworkingSpace(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonCoworkingSpaceActionPerformed

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        // TODO add your handling code here:
        new Laporan(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonLaporanActionPerformed

    private void buttonPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPengembalianActionPerformed
        // TODO add your handling code here:
        new Pengembalian(i, n, e).setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonPengembalianActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        PreparedStatement ps;
        
        String email = labelEmail.getText();
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/community_center", "root", "");
            java.util.Date date = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
            
            int a = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Logout?");
            
            if (a == JOptionPane.YES_OPTION) {
                String query = "UPDATE login SET tanggal_logout=?, waktu_logout=?, status=2 "
                        + "WHERE email=? AND status=1";
                ps = conn.prepareStatement(query);
                ps.setDate(1, sqlDate);
                ps.setTimestamp(2, sqlTime);
                ps.setString(3, email);
                ps.executeUpdate();
                
                new Login().setVisible(true);
                
                this.dispose();
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi ke Database Gagal.\n" + e);
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAudio;
    private javax.swing.JButton buttonBooking;
    private javax.swing.JButton buttonBuku;
    private javax.swing.JButton buttonCoworkingSpace;
    private javax.swing.JButton buttonLaporan;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMember;
    private javax.swing.JButton buttonPengembalian;
    private javax.swing.JButton buttonPinjam;
    private javax.swing.JButton buttonPoS;
    private javax.swing.JButton buttonToy;
    private javax.swing.JButton buttonVideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
